// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKrWMTx1eax4hXyhpZR-LHCwYnfVfi708',
    appId: '1:990827626908:web:87af6b80d3bcb450938859',
    messagingSenderId: '990827626908',
    projectId: 'fir-ex-3568b',
    authDomain: 'fir-ex-3568b.firebaseapp.com',
    storageBucket: 'fir-ex-3568b.firebasestorage.app',
    measurementId: 'G-209WY5W96H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1EU8xNNkAAdI4sP4j4Alg6kI6tHY3_W4',
    appId: '1:990827626908:android:c1bec20321fd0870938859',
    messagingSenderId: '990827626908',
    projectId: 'fir-ex-3568b',
    storageBucket: 'fir-ex-3568b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACAId0wQhwMXdIZX1ezbP38JMoJmJiQHI',
    appId: '1:990827626908:ios:c1d08ee3cb8cb977938859',
    messagingSenderId: '990827626908',
    projectId: 'fir-ex-3568b',
    storageBucket: 'fir-ex-3568b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseEx',
  );
}
