// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYTtLUZ6xJxxb6zWMr0lc4_5XsBNBkRto',
    appId: '1:441863888484:web:83fd2aaee93ce83f6f0971',
    messagingSenderId: '441863888484',
    projectId: 'punworld-app',
    authDomain: 'punworld-app.firebaseapp.com',
    storageBucket: 'punworld-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC55lrAaUMIDmolD8fV9zeQx-rPub47G2s',
    appId: '1:441863888484:android:93cc5080e3effdc86f0971',
    messagingSenderId: '441863888484',
    projectId: 'punworld-app',
    storageBucket: 'punworld-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASaC1j9KEaoMcgS8xIn2lA2f7uCGaTn3A',
    appId: '1:441863888484:ios:60b77725bfcc8fe06f0971',
    messagingSenderId: '441863888484',
    projectId: 'punworld-app',
    storageBucket: 'punworld-app.firebasestorage.app',
    iosBundleId: 'com.example.punworldApp',
  );
}
